{% set name = "nceplibs-sp" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-sp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aec475ccb5ccf7c5a758dfb699626f2be78a22729a9d8d5e0a286db6a3213a51

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - cmake
    - pkg-config >=0.21
    - make                  # [not win]
    - ninja                 # [win]
  host:
    - llvm-openmp

test:
  commands:
    - test -f ${PREFIX}/lib/libsp_4${SHLIB_EXT} -o -f ${PREFIX}/lib/libsp_d${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-sp
  summary: The spectral transform library (splib) contains FORTRAN subprograms to be used for a variety of spectral transform functions.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - EricEngle-NOAA
    - timcera
